AllCops:
  Excludes:
    - tmp/**
    - vendor/**
    - config/compass.rb
  RunRailsCops: true

# Not valid for Rails 3.
ActionFilter:
  Enabled: false

AlignHash:
  Enabled: false

AlignParameters:
  Enabled: false

BlockNesting:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    find: 'detect'

CyclomaticComplexity:
  Enabled: false

# Not valid for mongoid
DefaultScope:
  Enabled: false

Documentation:
  Enabled: false

Encoding:
  Enabled: false

FavorUnlessOverNegatedIf:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

IfUnlessModifier:
  Enabled: false

IndentHash:
  EnforcedStyle: consistent

Lambda:
  Enabled: false

LineLength:
  Enabled: false

LiteralInInterpolation:
  Enabled: false

MethodLength:
  Enabled: false

OneLineConditional:
  Enabled: false

Output:
  Exclude:
    - db/migrate/**

ParenthesesAroundCondition:
  Enabled: false

RedundantSelf:
  Enabled: false

SignalException:
  Enabled: false

SpaceAfterControlKeyword:
  Enabled: false

StringLiterals:
  Enabled: false

TrailingComma:
  Enabled: false

WhileUntilModifier:
  Enabled: false
